### ISSUE TITLE
Potentially infinite leather exploit in Fresh Meat

### ISSUE THREAD

**Issue by CrowCorvus** [paradigmnomad/PPJA#239]
I'm playing with a lot of mods so it's possible this could be a compatibility thing, but when you have a full inventory and try to harvest a meat crop that can drop leather while standing in it, it will just continue to drop leather onto the ground as long as you are holding the button to harvest. I have tested this on Pork and Chevon so far and it worked on both, so I would assume it works on the other leather producers. Smapi doesn't produce any text or errors when this happens, but I'll send my log anyway so you know what mods I'm using.
[https://smapi.io/log/c36f4bbe17a94fcb8d77084ea5101be7](url) (all of the update notifs are for ones that didn't update their manifest properly)

**Comment by paradigmnomad** [comment]
This shouldn't be an issue related to PPJA since PPJA is just content packs, but rather one of the frameworks. Leather is handled by Multi Yield Crops so I would recommend reporting it on that Nexus page. That's an interesting bug but it seems like you can reliably reproduce it which will help the mod author track down the cause if it can be fixed.
