### ISSUE TITLE
Workbench weirdness with Artisan Valley

### ISSUE THREAD

**Issue by Stifling-Bossness** [paradigmnomad/PPJA#31]
When viewing Artisan Valley machines in the workbench crafting menu, the names are incorrect and highlighted even if you lack the materials to make them. When viewed from the character crafting menu, all works as intended.

![](https://i.imgur.com/u5u64NV.jpg)

**Comment by paradigmnomad** [comment]
This is one of the many known issues going on with CFR right now. There isn't anything I can do to fix it sadly. It's frustrating. You can try the [unofficial update](https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-4.156000/page-26#post-3354284) and see if that helps to fix things.

Closing this because this is not something I can fix as it is a CFR issue.
