### ISSUE TITLE
Farmer to Florist mod

### ISSUE THREAD

**Issue by waterscaped** [paradigmnomad/PPJA#333]
Hello,

I have been using the Farmer to Florist mod but the Mail isn't working correctly. I will get letters from people saying they are giving me recipes or gifts, but nothing shows up at the bottom. I almost have every other PPJA mod installed and they all work fine, it is just the Farmer to Florist one.

Here is my SMAPI log: https://smapi.io/log/70bee1b6852e4ea6b7b8732dc715d062

Additionally, would it be possible to remove the gray text in the description of the items in shop menus? 

Thank you.

**Comment by lindidou** [comment]
Having the same problem here. Did u find out how to fix it?

**Comment by waterscaped** [comment]
> Having the same problem here. Did u find out how to fix it?

I did not, unfortunately. For now I just uninstalled the mod.

**Comment by JTBWatchDog** [comment]
Having this same issue as well

**Comment by miestasmia** [comment]
There are many issues with the DGA version of PPJA mods. Currently it is best to continue using the JA version.

**Comment by Raffy1988** [comment]
me and my wife have the same problem.
i followed the installing instructions on nexusmods. i use vortex, so all four folders are in my mod folder of stardew valley.
how can i use the JA version? and does this work?

**Comment by lindidou** [comment]
Im using the JA Version too now and yes, it works. U can find it on the Nexus-Mod Page. If u scroll a little bit down, u can find a section that says „Old Versions" - there is the JA Version of the MOD.

**Comment by Raffy1988** [comment]
I noticed, that there are some Folders which are "duplicates" the only difference are the letters in front between the brackets, e.g. [FTM], [CP], [JA] and a few others.
i few, i know: FTM = Farm Type Manager, CP = Content Patcher.

I thought I have to put them all in my Common/SDV/Mod folder.
But after your response it seems, this was the wrong way.

I am really no expert in modding, or using mods ^^

Could someone explain to me, whats the difference in these folders, and why there are so many different "versions"?
It may seem as a dumb question, but I would like to understand the whole structure behind it.

**Comment by IceMaverick** [comment]
@waterscaped @lindidou This is currently caused by the problem that the version uploaded to Nexus is not actually the most recent version available here on GitHub. Specifically, the "[MFM] Farmer to Florist" folder is out of date on the Nexus. Inside that folder is a file named "mail.json" that has a more recent version available here on Github that fixes this problem.

The actual issue itself is that mail.json calls the item "Potted Tulip_Recipe" when it should be "Converted_Potted Tulip_Recipe". I think there's a couple of other potted plant recipes that have the same issue in the Nexus version, but the Tulip is the first one. If you download Florist to Farmer from here on GitHub, delete the copy you have installed, and then install this copy, it should work as expected.

---------------------------------------------

@Raffy1988 The folders are not duplicates of each other at all, they're all necessary. The brackets at the front are - as you stated - related to the pre-req mod that the files inside interact with. All of the files inside of the [CP]ModName folder are the files that are loaded with Content Patcher, the files inside [DGA]ModName are the ones that are loaded by Dynamic Game Assets, and so on. Each of these pre-requisites are a library of functionality that focus on altering the game in their own specific way, and by the combined powers of all of them, you get the functioning PPJA mod as the author intended.

**Comment by waterscaped** [comment]
> @waterscaped @lindidou This is currently caused by the problem that the version uploaded to Nexus is not actually the most recent version available here on GitHub. Specifically, the "[MFM] Farmer to Florist" folder is out of date on the Nexus. Inside that folder is a file named "mail.json" that has a more recent version available here on Github that fixes this problem.
> 
> The actual issue itself is that mail.json calls the item "Potted Tulip_Recipe" when it should be "Converted_Potted Tulip_Recipe". I think there's a couple of other potted plant recipes that have the same issue in the Nexus version, but the Tulip is the first one. If you download Florist to Farmer from here on GitHub, delete the copy you have installed, and then install this copy, it should work as expected.

Will the DGA version work evben if I have JA

**Comment by IceMaverick** [comment]
Yes, the DGA version does work with other, independent JA mods that add stuff, but be aware of two things:

1. You shouldn't use the DGA version and the JA version of the same mod at the same time. (I.e. don't use multiple versions of Farmer to Florist, just pick either JA or DGA).

2. A lot of supporting mods for PPJA like Miller Time, Producer Framework Mod, etc. don't currently support DGA and thus won't recognize items added by it. This will mean having those mods installed will cause the logs to complain that it can't find items for machines or certain recipes and they wont work as intended. Many authors of those supporting mods have said they won't be updating for any kind of DGA version until after Stardew 1.6 releases.

**Comment by waterscaped** [comment]
> Yes, the DGA version does work with other, independent JA mods that add stuff, but be aware of two things:
> 
> 1. You shouldn't use the DGA version and the JA version of the same mod at the same time. (I.e. don't use multiple versions of Farmer to Florist, just pick either JA or DGA).
> 2. A lot of supporting mods for PPJA like Miller Time, Producer Framework Mod, etc. don't currently support DGA and thus won't recognize items added by it. This will mean having those mods installed will cause the logs to complain that it can't find items for machines or certain recipes and they wont work as intended. Many authors of those supporting mods have said they won't be updating for any kind of DGA version until after Stardew 1.6 releases.

Thank you for the help. I deleted the DGA version of the mod from my folder and downloaded the older JA version. It is working perfectly now.
