### ISSUE TITLE
Suggestion: Canner

### ISSUE THREAD

**Issue by Rametteperegrine** [paradigmnomad/PPJA#94]
I don't know how this works, I'm a complete newbie but I've recently discovered these mods and I'm loving how they work with Automate and the Deluxe Autograbber unofficial mod. I've always hated how there was some crops/forage you couldn't really do anything with and this has been great. I am noticing a few things that still are dead ends though, mostly beach forage. Clams, oysters, and cockles still don't do anything  (unless I just haven't found it yet, in which case please, enlighten me) I thought perhaps a new machine could solve this. I was thinking about a canner. I use a pressure canner IRL and you can Jar most anything including meat and fish. Obviously you could also have canned veggies too which would give you a logical way to do things like corn and such (who would really eat pickled corn?) I have plenty of free time and a willingness to learn if there is any way I can help but I have zero experience in any kind of coding and I'm not really artistic.

**Comment by paradigmnomad** [comment]
Very interesting. We have some changes to Fresh Meat coming soon which could benefit from having a canary machine. I'll pass this onto the others to get their thoughts as well!

**Comment by paradigmnomad** [comment]
![CanMachineShow](https://user-images.githubusercontent.com/34044924/75085259-64052180-54f5-11ea-8169-0d471ae9d364.gif) 

Undare was kind enough to make us a canning machine! This will be included in a future update most likely to Fresh Meat. Currently, canned items will be in glass jars similar to the pickled item sprite. More mason jar style rather than industrial canning.

**Comment by Rametteperegrine** [comment]
Great! Awesome. Will you be able to can oysters clams and fish?
